name: Renovate

on:
  schedule:
    - cron: "7 * * * *" # run hourly
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    env:
      RENOVATE_REPOSITORIES: ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Run Renovate
        uses: renovatebot/github-action@v44.2.0
        with:
          renovate-image: ghcr.io/renovatebot/renovate
          token: ${{ secrets.RENOVATE_TOKEN }}